### ISSUE TITLE
https://mcl.host/ has a self signed cert

### ISSUE THREAD

**Issue by SvenDowideit** [prologic/minimal-container-linux#17]
letsencrypt is everyone's friend :p

**Comment by steve-todorov** [comment]
I see you're using `traefik` as a revers proxy. I was playing around with `traefik` a few weeks ago and [here's](https://gist.github.com/steve-todorov/465391b3b4ac1649bb4d215ee989d38d) the configuration which I'm using. This automatically issues a `letsencrypt` certificate when you create a new container which has the proper labels (`traefik.enable=true` and `raefik.frontend.rule=Host:the-name-of-the-domain`) and also automatically renews them. Hope it helps you out :)

**Comment by prologic** [comment]
For some reason I missed this Issue (*and a few others it seems*) Sorry about that! This is resolved now and am just hosting docs on Github Pages. Closing :)
