### ISSUE TITLE
Services as container?

### ISSUE THREAD

**Issue by pwFoo** [prologic/minimal-container-linux#18]
Is a service (= container) management (start, stop, enable, dependencies, update,...) planned for mcl?

**Comment by prologic** [comment]
Sorry I missed this issue :/ Can you elaborate on what you're asking here? mcl already comes pre-packaged with a running Docker Daemon (*needs updating*)

**Comment by prologic** [comment]
> mcl is a minimal OS running docker (daemon)?

This is correct. It is designed to run containers. Right now it ships with a Docker Container runtime. You can run things like:

```#!bash
$ docker run -d -p 8000:8000 prologic/hello-go
```

> What is about system services like dhcp, ntp oder other services / apps? Is there a concept to run such services as containers / compose? Any alternative for init scripts / chkconfig / sytemctl service management?

A DHCP client is builtin and the network is automatically configured.

There is also support (*although not tested very well*) for CloudInit.

MCL also runs an SSH daemon (*Dropbear*) for remote connectivity and management.

It however doesn't have a traditional init system like System V or `systemd`, etc. It just configures the network, hostname and runs the Docker daemon and presents a very basic shell.
 
> I would like to test it. Haven't found install / build instructions?

Please do! Documentation is unfortunately very sparse at the moment; but PRs welcome and it makes sense to populate out a `./docs/` section in the repo (*which should get built out into the website too*).

As far as installation goes; there is none. You just boot the ISO.

The only other thing that matters is a block storage device labelled `DOCKER_DATA` (*e.g: a disk*). This will be used as `/var/run/docker` if it finds such a labelled disk at boot-up. This is how you can persist state in the form of running Docker containers.

**Comment by prologic** [comment]
Starting to flesh out some better docs over at https://mcl.host/ -- Feel free to help out ❤️

**Comment by pwFoo** [comment]
Thanks I'll take a look and do some tests in the next days

**Comment by prologic** [comment]
Thanks! Feel free to open a new issue if you face any other lacking documentation or issues!
