### ISSUE TITLE
Build initrd / kernel additional to the iso?

### ISSUE THREAD

**Issue by pwFoo** [prologic/minimal-container-linux#19]
Would it possible to build initrd / kernel additional to the iso?
initrd / kernel could be added to the bootloader and is similar to an installed version with data (/var/lib/docker) persistence.

**Comment by pwFoo** [comment]
That command should build a initrd?
```
find . |  cpio -H newc -o | gzip > /tmp/initd
```
Maybe could be added to build script?

**Comment by pwFoo** [comment]
@prologic 
rootfs == initrd. So could be just renamed?
Successfully booted kernel + rootfs.

**Comment by pwFoo** [comment]
@prologic @ivandavidov 
I think there are two options.

1. rename it to initrd.gz or 
1. rootfs.gz with some more information in the documentation that it could be used as initrd?

Both are fine for me 👍

**Comment by prologic** [comment]
> Just a comment from my side - if I remember correctly, you can't name the rootfs/initramfs archive `blahblah.tar.gz`. You have to name it `blahblah.something`. If you use more than one dot in the name, either the boot loader or the kernel gets confused and you end up with kernel panic.

That's why I opted for just `rootfs.gz` :)

**Comment by prologic** [comment]
> @prologic @ivandavidov
> I think there are two options.
> 
> 1. rename it to initrd.gz or
> 2. rootfs.gz with some more information in the documentation that it could be used as initrd?
> 
> Both are fine for me 👍

As I said; happy to accept a PR in either case. I went for `rootfz.gz` originally because it was moreintuitivee in my mind (*but I not have picked the name most commonly used and recognized by folks in this field of "developing your own Distro"*)

**Comment by pwFoo** [comment]
Works fine with rootfs.gz and won't be needed if linuxkit is used as build framework (#23).
