### ISSUE TITLE
Proposal: provide screenshot with simple Docker app (e.g. hello-world)

### ISSUE THREAD

**Issue by ivandavidov** [prologic/minimal-container-linux#20]
I think it would be great if you provide additional screenshots in the documentation, including a screenshot which demonstrates that the Docker functionality actually works. In that way MCL will be easier to spot and much more appealing to the audience.

**Comment by prologic** [comment]
Damn I missed this issue! So sorry; Will do :) Kicking up some steam for MCL lately :D
