### ISSUE TITLE
kernel auto config ip=dhcp

### ISSUE THREAD

**Issue by pwFoo** [prologic/minimal-container-linux#28]
Hi @prologic 
what do you think about kernel ip configuration feature?
Tested with my dell notebook connected to my fritzbox router.

kernel config options
```
config y IP_PNP
config y IP_PNP_DHCP
```

enable with kernel cmd / options
```
ip=dhcp
```
DOn't know if there is a way to trigger that from for example /init instead of kernel cmd line.

dmesg output
```
[    3.973841] e1000: eth0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[    3.981016] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    3.992871] Sending DHCP requests ., OK
[    3.994777] IP-Config: Got DHCP answer from 10.0.2.2, my address is 10.0.2.15
[    3.997084] IP-Config: Complete:
[    3.998330]      device=eth0, hwaddr=52:54:00:12:34:56, ipaddr=10.0.2.15, mask=255.255.255.0, gw=10.0.2.2
[    4.001862]      host=10.0.2.15, domain=, nis-domain=(none)
[    4.003971]      bootserver=10.0.2.2, rootserver=10.0.2.2, rootpath=
[    4.003972]      nameserver0=10.0.2.3
```

Routing and interface config will be fine, but DNS is missing.

Workaround DNS
```
NAMESERVERS=$(dmesg | grep -Eo -m2 "nameserver[0-9]=[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}" | sed "s/nameserver[0-9]=//g")

> /etc/resolv.conf
for DNS in $NAMESERVERS; do
        echo "nameserver $DNS" >> /etc/resolv.conf
done

```
Tested with single DNS, not multiple DNS given by DHCP.
Replaced the udhcpd

**Comment by prologic** [comment]
Oh that's neat! Didn't know the Kernel has a builtin DHCP client.
Any way to avoid parsing dmesg? Can scripts be triggered?

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by pwFoo** [comment]
Haven't found a way for that, but I'm new with that kernel feature too. Maybe I'll find some more information about that.

I just need it for initial network setup. Services (mdevd, dhcpcd, rngd, ...) will be running inside of containers in my setup. Similar to linuxkit onboot and services.

**Comment by prologic** [comment]
Sounds reasonable

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by pwFoo** [comment]
Sounds like there is no way to do it.
https://mohammadthalif.wordpress.com/2011/04/28/how-to-use-dhcp-in-linux/

```
Kernel level auto-configuration:

To use kernel level auto configurtion select below options in the Linux kernel configuration.

-> Networking support (NET [=y])
-> Networking options
-> TCP/IP networking (INET [=y])
[*]   IP: kernel level autoconfiguration
[*]     IP: DHCP support

Advantage:
In case of your root file system in NFS and wanted to have a IP dynamicaly configirued though DHCP, kernel level DHCP will come to rescue you. Using kernel level DHCP you will have have a valid IP address by the time the Linux kernel have completed the booting and can immediately mount an NFS root file system.


Disadvantage:
1. Can only configure basic network parameters, which do not include items such as DNS servers.
```

**Comment by prologic** [comment]
@pwFoo I _think_ this can be added (_the kernel options that is_) and the `ip=dhcp` left up to the end-user to control via `cmdline` or `append=` bootloader options if that's what they want.

What do you think?

**Comment by pwFoo** [comment]
Yes, would be fine for me.

**Comment by prologic** [comment]
I'll add the option and test it shortly.
