### ISSUE TITLE
rngd doesn't start with "-f" if condition?

### ISSUE THREAD

**Issue by pwFoo** [prologic/minimal-container-linux#29]
With my own build rngd doesn't start. It looks like a problem with the if 
https://github.com/prologic/minimal-container-linux/blob/master/rootfs/init#L46

/dev/hwrng isn't a regular file (-f)? Should be `-c` or `-e`?

And is /dev/hwrng better than /dev/random or /dev/urandom?

**Comment by pwFoo** [comment]
# changed "-f" to "-c" inf if condition for device check
# moved to from /dev/hwrng to /dev/urandom
# moved up rngd start before udhcpc to have entropy earlier

Reduced crng init time from 180+ seconds to 2 seconds

**Comment by pwFoo** [comment]
@prologic 

1. changed "-f" to "-c" inf if condition for device check
1. moved to from /dev/hwrng to /dev/urandom
1. moved up rngd start before udhcpc to have entropy earlier

Reduced crng init time from 180+ seconds to 2 seconds

**Comment by prologic** [comment]
It *may* be that the `-f` expression is wrong (*I'll have to re-test*) but `/dev/hwrng` is a hardware emulated PRNG from QEMU. This is mostly useful in a virtual environment. In real hardware environments there should be ample entropy that rngd isn't necessary at all (*hence the conition start*) -- FWIW it tooks some weeks of research to iron out all the details here.

**Comment by pwFoo** [comment]
Boot time with qemu (kvm enabled) and hardware (dell notebook) the boot was very slow until docker works. Round about 3 minutes with qemu and 1 minute with hw until crng finished. docker ps waits for that until I get an response.

That's way I played with rngd and also tested `random.trust_cpu=on|off` as kernel boot param.

For the moment it works with rngd and /dev/urandom. I think I have to test it after some other things...
