### ISSUE TITLE
Missing Network Drivers

### ISSUE THREAD

**Issue by prologic** [prologic/minimal-container-linux#9]
We're missing a few important Network drivers:

* virtio
* Intel e100
* rtl*
* vmx*

**Comment by ivandavidov** [comment]
Just for reference - long time ago I successfully integrated the MINCS container runtime in MLL. Here is the list of drivers and kernel settings that I used:

https://github.com/ivandavidov/minimal/blob/mincs/src/02_build_kernel.sh#L121

Probably it could be of some help. :)

**Comment by prologic** [comment]
Thank you :)

**Comment by prologic** [comment]
Mind if I steal your `yconfig` and `nconfig` functions? I like them over my `config` func :)

**Comment by ivandavidov** [comment]
Be my guest, steal all the code you want. :)

I stole the original ``yconfig`` function from the [Boot2Minc](https://github.com/mhiramat/boot2minc/blob/master/src/2_build_kernel.sh#L42) project and I liked it so much, that I created corresponding ``nconfig``.

**Comment by prologic** [comment]
Nice ;)

**Comment by prologic** [comment]
So really #10 just covers Proxmox VE and Virtualbox (*for now*). We still may be missing *some* drivers for other virtualization platforms such as those used by DigitalOcean, Vultr AWS, GCE, etc.

**Comment by prologic** [comment]
[Vultr](https://vultr.com) confirmed:

```
$ ssh root@104.156.231.119 minimal
Minimal Container Linux (MCL) v0.0.3
```

**Comment by prologic** [comment]
Can't confirm [DigitalOcean](https://digitalocean.com) as there is no way to upload or use Custom ISO(s)

**Comment by prologic** [comment]
Anyone got an AWS account to test EC2?
